acceptedDeal Object {
    "_id": "608129f86c6951a9406bfcaf",
    "brand": Object {
      "category": "Fashion & Accessories",
      "img": "https://storage.googleapis.com/rabbitx/1612340650270photo.jpg",
      "name": "UnityFilm",
      Symbol(mobx administration): ObservableObjectAdministration {
        "defaultEnhancer": [Function deepEnhancer],
        "keysAtom": Atom {
          "diffValue": 0,
          "isBeingObserved": false,
          "isPendingUnobservation": false,
          "lastAccessedBy": 0,
          "lowestObserverState": 2,
          "name": "DealStore@3.deals.counterPending.data[..].brand.keys",
          "observers": Set {},
        },
        "name": "DealStore@3.deals.counterPending.data[..].brand",
        "pendingKeys": Map {
          "$$typeof" => false,
          Symbol(Symbol.toStringTag) => false,
          "toJSON" => false,
          "hasOwnProperty" => false,
        },
        "proxy": [Circular],
        "target": Object {
          "category": "Fashion & Accessories",
          "img": "https://storage.googleapis.com/rabbitx/1612340650270photo.jpg",
          "name": "UnityFilm",
          Symbol(mobx administration): [Circular],
        },
        "values": Map {
          "category" => "Fashion & Accessories",
          "img" => "https://storage.googleapis.com/rabbitx/1612340650270photo.jpg",
          "name" => "UnityFilm",
        },
      },
    },
    "coverImg": "https://storage.googleapis.com/rabbitx/1614069101501photo.jpg",
    "dealContact": Object {
      "dealContactId": "DCRGE3p6E",
      Symbol(mobx administration): ObservableObjectAdministration {
        "defaultEnhancer": [Function deepEnhancer],
        "keysAtom": Atom {
          "diffValue": 0,
          "isBeingObserved": false,
          "isPendingUnobservation": false,
          "lastAccessedBy": 0,
          "lowestObserverState": 2,
          "name": "DealStore@3.deals.counterPending.data[..].dealContact.keys",
          "observers": Set {},
        },
        "name": "DealStore@3.deals.counterPending.data[..].dealContact",
        "pendingKeys": Map {
          "$$typeof" => false,
          Symbol(Symbol.toStringTag) => false,
          "toJSON" => false,
          "hasOwnProperty" => false,
        },
        "proxy": [Circular],
        "target": Object {
          "dealContactId": "DCRGE3p6E",
          Symbol(mobx administration): [Circular],
        },
        "values": Map {
          "dealContactId" => "DCRGE3p6E",
        },
      },
    },
    "dealId": "7dUHm00ii",
    "dueDate": "2021-05-31T16:59:00.000Z",
    "name": "2test nego isNegotiateScopeOfWorks",
    "startDate": "2021-04-20T17:00:00.000Z",
    Symbol(mobx administration): ObservableObjectAdministration {
      "defaultEnhancer": [Function deepEnhancer],
      "keysAtom": Atom {
        "diffValue": 0,
        "isBeingObserved": false,
        "isPendingUnobservation": false,
        "lastAccessedBy": 206,
        "lowestObserverState": 0,
        "name": "DealStore@3.deals.counterPending.data[..].keys",
        "observers": Set {},
      },
      "name": "DealStore@3.deals.counterPending.data[..]",
      "pendingKeys": Map {
        "$$typeof" => false,
        Symbol(Symbol.toStringTag) => false,
        "toJSON" => false,
        "hasOwnProperty" => false,
      },
      "proxy": [Circular],
      "target": Object {
        "_id": "608129f86c6951a9406bfcaf",
        "brand": Object {
          "category": "Fashion & Accessories",
          "img": "https://storage.googleapis.com/rabbitx/1612340650270photo.jpg",
          "name": "UnityFilm",
          Symbol(mobx administration): ObservableObjectAdministration {
            "defaultEnhancer": [Function deepEnhancer],
            "keysAtom": Atom {
              "diffValue": 0,
              "isBeingObserved": false,
              "isPendingUnobservation": false,
              "lastAccessedBy": 0,
              "lowestObserverState": 2,
              "name": "DealStore@3.deals.counterPending.data[..].brand.keys",
              "observers": Set {},
            },
            "name": "DealStore@3.deals.counterPending.data[..].brand",
            "pendingKeys": Map {
              "$$typeof" => false,
              Symbol(Symbol.toStringTag) => false,
              "toJSON" => false,
              "hasOwnProperty" => false,
            },
            "proxy": [Circular],
            "target": Object {
              "category": "Fashion & Accessories",
              "img": "https://storage.googleapis.com/rabbitx/1612340650270photo.jpg",
              "name": "UnityFilm",
              Symbol(mobx administration): [Circular],
            },
            "values": Map {
              "category" => "Fashion & Accessories",
              "img" => "https://storage.googleapis.com/rabbitx/1612340650270photo.jpg",
              "name" => "UnityFilm",
            },
          },
        },
        "coverImg": "https://storage.googleapis.com/rabbitx/1614069101501photo.jpg",
        "dealContact": Object {
          "dealContactId": "DCRGE3p6E",
          Symbol(mobx administration): ObservableObjectAdministration {
            "defaultEnhancer": [Function deepEnhancer],
            "keysAtom": Atom {
              "diffValue": 0,
              "isBeingObserved": false,
              "isPendingUnobservation": false,
              "lastAccessedBy": 0,
              "lowestObserverState": 2,
              "name": "DealStore@3.deals.counterPending.data[..].dealContact.keys",
              "observers": Set {},
            },
            "name": "DealStore@3.deals.counterPending.data[..].dealContact",
            "pendingKeys": Map {
              "$$typeof" => false,
              Symbol(Symbol.toStringTag) => false,
              "toJSON" => false,
              "hasOwnProperty" => false,
            },
            "proxy": [Circular],
            "target": Object {
              "dealContactId": "DCRGE3p6E",
              Symbol(mobx administration): [Circular],
            },
            "values": Map {
              "dealContactId" => "DCRGE3p6E",
            },
          },
        },
        "dealId": "7dUHm00ii",
        "dueDate": "2021-05-31T16:59:00.000Z",
        "name": "2test nego isNegotiateScopeOfWorks",
        "startDate": "2021-04-20T17:00:00.000Z",
        Symbol(mobx administration): [Circular],
      },
      "values": Map {
        "_id" => "608129f86c6951a9406bfcaf",
        "name" => "2test nego isNegotiateScopeOfWorks",
        "startDate" => "2021-04-20T17:00:00.000Z",
        "dueDate" => "2021-05-31T16:59:00.000Z",
        "dealId" => "7dUHm00ii",
        "dealContact" => Object {
          "dealContactId": "DCRGE3p6E",
          Symbol(mobx administration): ObservableObjectAdministration {
            "defaultEnhancer": [Function deepEnhancer],
            "keysAtom": Atom {
              "diffValue": 0,
              "isBeingObserved": false,
              "isPendingUnobservation": false,
              "lastAccessedBy": 0,
              "lowestObserverState": 2,
              "name": "DealStore@3.deals.counterPending.data[..].dealContact.keys",
              "observers": Set {},
            },
            "name": "DealStore@3.deals.counterPending.data[..].dealContact",
            "pendingKeys": Map {
              "$$typeof" => false,
              Symbol(Symbol.toStringTag) => false,
              "toJSON" => false,
              "hasOwnProperty" => false,
            },
            "proxy": [Circular],
            "target": Object {
              "dealContactId": "DCRGE3p6E",
              Symbol(mobx administration): [Circular],
            },
            "values": Map {
              "dealContactId" => "DCRGE3p6E",
            },
          },
        },
        "brand" => Object {
          "category": "Fashion & Accessories",
          "img": "https://storage.googleapis.com/rabbitx/1612340650270photo.jpg",
          "name": "UnityFilm",
          Symbol(mobx administration): ObservableObjectAdministration {
            "defaultEnhancer": [Function deepEnhancer],
            "keysAtom": Atom {
              "diffValue": 0,
              "isBeingObserved": false,
              "isPendingUnobservation": false,
              "lastAccessedBy": 0,
              "lowestObserverState": 2,
              "name": "DealStore@3.deals.counterPending.data[..].brand.keys",
              "observers": Set {},
            },
            "name": "DealStore@3.deals.counterPending.data[..].brand",
            "pendingKeys": Map {
              "$$typeof" => false,
              Symbol(Symbol.toStringTag) => false,
              "toJSON" => false,
              "hasOwnProperty" => false,
            },
            "proxy": [Circular],
            "target": Object {
              "category": "Fashion & Accessories",
              "img": "https://storage.googleapis.com/rabbitx/1612340650270photo.jpg",
              "name": "UnityFilm",
              Symbol(mobx administration): [Circular],
            },
            "values": Map {
              "category" => "Fashion & Accessories",
              "img" => "https://storage.googleapis.com/rabbitx/1612340650270photo.jpg",
              "name" => "UnityFilm",
            },
          },
        },
        "coverImg" => "https://storage.googleapis.com/rabbitx/1614069101501photo.jpg",
      },
    },
  }